# Generated by Django 4.1.1 on 2022-10-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='table',
        ),
    ]
