# Generated by Django 4.1.1 on 2022-10-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_table_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='table',
        ),
    ]
