# Generated by Django 4.1.1 on 2022-10-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
